### ISSUE TITLE
Issue with downloading kernels

### ISSUE THREAD

**Issue by imitevski** [tyfolino/climkern#10]
After the download completes the following error appears: 

(ck_env2) -bash-4.2$ python -m climkern download
Downloading data from 'doi:10.5281/zenodo.10223376/data.zip' to file '/home/im2527/miniconda3/envs/ck_env2/lib/python3.9/site-packages/climkern/data.zip'.
100%|█████████████████████████████████████| 5.63G/5.63G [00:00<00:00, 14.3TB/s]
Traceback (most recent call last):
  File "/home/im2527/miniconda3/envs/ck_env2/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/im2527/miniconda3/envs/ck_env2/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/im2527/miniconda3/envs/ck_env2/lib/python3.9/site-packages/climkern/__main__.py", line 17, in <module>
    plac.call(commands[command], sys.argv[1:])
  File "/home/im2527/miniconda3/envs/ck_env2/lib/python3.9/site-packages/plac_core.py", line 436, in call
    cmd, result = parser.consume(arglist)
  File "/home/im2527/miniconda3/envs/ck_env2/lib/python3.9/site-packages/plac_core.py", line 287, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "/home/im2527/miniconda3/envs/ck_env2/lib/python3.9/site-packages/climkern/download.py", line 12, in download
    f_in = retrieve(
  File "/home/im2527/miniconda3/envs/ck_env2/lib/python3.9/site-packages/pooch/core.py", line 239, in retrieve
    stream_download(url, full_path, known_hash, downloader, pooch=None)
  File "/home/im2527/miniconda3/envs/ck_env2/lib/python3.9/site-packages/pooch/core.py", line 808, in stream_download
    hash_matches(tmp, known_hash, strict=True, source=str(fname.name))
  File "/home/im2527/miniconda3/envs/ck_env2/lib/python3.9/site-packages/pooch/hashes.py", line 176, in hash_matches
    raise ValueError(
ValueError: MD5 hash of downloaded file (data.zip) does not match the known hash: expected md5:8718deb9ed358dde36f3a9c1fd8a46c4 but got d9ac906f26ac34a137d9241cbd2dafae. Deleted download for safety. The downloaded file may have been corrupted or the known hash may be outdated.

**Comment by tyfolino** [comment]
I am going to work on this this weekend! Should be a relatively easy fix.

**Comment by tyfolino** [comment]
Feel free to test using the latest version from the dev branch. I can reopen if necessary.

**Comment by imitevski** [comment]
Still same error:

(ck_env) mitevski@mitevski ~ % python -m climkern download                          
Downloading data from 'doi:10.5281/zenodo.10223376/data.zip' to file '/opt/anaconda3/envs/ck_env/lib/python3.9/site-packages/climkern/data.zip'.
100%|█████████████████████████████████████| 5.63G/5.63G [00:00<00:00, 11.2TB/s]
Traceback (most recent call last):
  File "/opt/anaconda3/envs/ck_env/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/anaconda3/envs/ck_env/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/anaconda3/envs/ck_env/lib/python3.9/site-packages/climkern/__main__.py", line 17, in <module>
    plac.call(commands[command], sys.argv[1:])
  File "/opt/anaconda3/envs/ck_env/lib/python3.9/site-packages/plac_core.py", line 436, in call
    cmd, result = parser.consume(arglist)
  File "/opt/anaconda3/envs/ck_env/lib/python3.9/site-packages/plac_core.py", line 287, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "/opt/anaconda3/envs/ck_env/lib/python3.9/site-packages/climkern/download.py", line 12, in download
    f_in = retrieve(
  File "/opt/anaconda3/envs/ck_env/lib/python3.9/site-packages/pooch/core.py", line 239, in retrieve
    stream_download(url, full_path, known_hash, downloader, pooch=None)
  File "/opt/anaconda3/envs/ck_env/lib/python3.9/site-packages/pooch/core.py", line 808, in stream_download
    hash_matches(tmp, known_hash, strict=True, source=str(fname.name))
  File "/opt/anaconda3/envs/ck_env/lib/python3.9/site-packages/pooch/hashes.py", line 176, in hash_matches
    raise ValueError(
ValueError: MD5 hash of downloaded file (data.zip) does not match the known hash: expected md5:8718deb9ed358dde36f3a9c1fd8a46c4 but got d9ac906f26ac34a137d9241cbd2dafae. Deleted download for safety. The downloaded file may have been corrupted or the known hash may be outdated.

**Comment by tyfolino** [comment]
Hi Ivan,

I suspect you are redownloading the package from PyPI or TestPyPI. In order to test the update, please ```git pull``` to get the latest update to the ```dev``` channel and install the package locally via ```pip install /path/to/package```. 

Updates are eventually pushed to PyPI when a new release is issued.

**Comment by imitevski** [comment]
That worked. Thanks!
